### ISSUE TITLE
tunnel dsdl

### ISSUE THREAD

**Issue by olliw42** [UAVCAN/dsdl#46]
1) why [<=60]?
why not 59, or 66? Even 64 would be better frame usage than 60

2) protocol doesn't really make much sense, right. Especially if 0 is mavlink. 0 = default should be rather something like UNDEFINED/GENERIC/TRANSPARENT or whatever it is named. What instead would be seriously needed is some possibility to send meta data, such as baudrate, clock rate, etc. pp. See gps example in https://www.youtube.com/watch?v=Sw24wAIoemA.

my 2 c :)

**Comment by pavel-kirienko** [comment]
1. The objective was to make the message always fit into one CAN FD frame; 60 bytes is therefore the maximum.
2. The meaning of 0 is debatable. The tunneling feature is not intended for the exchange of raw/unstructured data; as I said a number of times previously, UAVCAN should not be used for raw data tunnelling as that partially defeats the purpose of the protocol. Obviously, anybody is free to define their own data types and use the protocol for whatever purpose suits them, but this use case will not be supported in the standard data type set.
