### ISSUE TITLE
Archive the vendor-specific DSDL repo

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/dsdl#55]
Archive the vendor-specific DSDL repo, update the README file here to indicate that this repository is supposed to contain all public definitions, both standard and vendor-specific.

Repo to be archived: https://github.com/UAVCAN/vendor-specific-dsdl

**Comment by kjetilkjeka** [comment]
A different proposal to how this can be done

https://forum.uavcan.org/t/simpler-and-better-dsdl-versioning/280
